In [3]:
import numpy as np
frontiers = np.array([[2,3],[3,4],[.1,.05]])
frontiers

array([[2.  , 3.  ],
       [3.  , 4.  ],
       [0.1 , 0.05]])

In [4]:
ref = np.array([0,0])
ref

array([0, 0])

In [5]:
distances = np.sqrt((frontiers[:,0]-ref[0])**2 + (frontiers[:,1]-ref[1])**2)
distances

array([3.60555128, 5.        , 0.1118034 ])

In [7]:
mask = (distances>0.2)
mask

array([ True,  True, False])

In [9]:
frontiers = frontiers[mask]
frontiers

array([[2., 3.],
       [3., 4.]])